import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import type { User } from 'shared-types';
import { I18nProvider } from '@hosts/components/I18nProvider';
import { APP_NAME } from 'shared-config';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: APP_NAME,
    description: 'Generated by create next app',
};

const dummyUser: User = {
    uid: 'test123',
    email: 'test@example.com',
    isEmailVerified: false,
    role: 'guest',
};

console.log('Dummy user:', dummyUser);
console.log('hello world');
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <I18nProvider>
                    {children}
                </I18nProvider>
            </body>
        </html>
    );
}
